name: flutter_small_boilerplate
description: A boilerplate for small Flutter app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  provider: ^6.0.2
  sentry_flutter: ^6.2.2
  shared_preferences: ^2.0.12
  sura_flutter: ^1.0.3
  sura_manager: ^1.0.0
  url_launcher: ^6.0.18
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/flutter-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
